# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ad960ccdd93a5ac2061952ff10fd1be5401cd5fa2adb06026bbbc57d0b6a0bfccee29ad565ad610115e39ce760d432c475c00cbc1a3a5865bbd810cd353e968

test:
  secret_key_base: 26a30c85c712fb01b9c4e802dd554b058d26bc1d114858365f1e6c3243a1671eed6f73a2e485d3403f84daccc39e7ec3482a4d4eaef1de08479cf5a94a0c48dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
